import threading
import time
import numpy as np
from time import time

class trainer_thread(threading.Thread):
    def __init__(self,trainer, runner_threads, train_epochs):
        threading.Thread.__init__(self)
        self.trainer = trainer
        self.runner_threads = runner_threads
        self.train_epochs = train_epochs

    def run(self):
        self.running = True
        t_collection_start = time()
        # current_idx       = [0 for _ in runners]
        # current_iteration = [1 for _ in runners] #These are for the non-primitive solution...
        all_data = []
        # while ( np.array(current_iteration) < self.train_epochs ).any():
        for r in self.runner_threads:
            '''PRIMITIVE SOLUTION!'''
            while r.running:
                pass
            '''
            DESIRABLE: start processing the first epoch on the samples
            generated by the runner, as they are coming in
            '''
            all_data += r.agent.get_train_data()
        t_training_start = time()
        print("Collection done after {} seconds!".format( t_training_start-t_collection_start ) )
        n = sum([len(t) for t in all_data ])

        print("Training on {} samples. Avg length=".format( str(n).rjust(6)), n/len(all_data) )

        self.trainer.do_training(all_data, self.train_epochs)
        self.trainer.model.save_weights()
        self.running = False
        return

    def join(self):
        while self.running:
            pass

class runner_thread(threading.Thread):
    def __init__(self, id, env, agent, steps, trainer):
        threading.Thread.__init__(self)
        self.id = id
        self.env = env
        self.s_prime = env.reset()
        self.agent = agent
        self.steps = steps
        self.trainer = trainer
        self.running = False

    def join(self):
        while self.running:
            pass

    def run(self):
        self.running = True
        if self.trainer.model.saved_weights is not None:
            self.agent.model.set_weights( self.trainer.model.saved_weights )
        for t in range(self.steps):
            s = self.s_prime
            a = self.agent.get_action(s)
            self.s_prime, r, done, _ = self.env.step(a)
            args = self.agent.remember((s,a,r,self.s_prime,done))
            if done:
                self.agent.end_episode(*args)
                self.s_prime = self.env.reset()
        if not done:
            self.agent.end_episode(*args)

        print("runner{} collected {} samples".format(self.id, self.steps))
        self.running = False
        return

class threaded_runner:
    def __init__(self, envs=None, runners=None, trainer=None, train_epochs=3, steps=0):
        self.threads = []
        runner_threads = []
        for i,ae in enumerate(zip(runners,envs)):
            a,e = ae
            thread = runner_thread(i, e, a, steps, trainer)
            self.threads.append(thread)
            runner_threads.append(thread)
        self.threads.append(trainer_thread(trainer,runner_threads, train_epochs))

    def target(self, agent):
        for thread in self.threads:
            thread.agent = agent

    def run(self):
        for thread in self.threads:
            thread.start()

    def join_all_threads(self):
        for thread in self.threads:
            thread.join()

    def join(self):
        self.join_all_threads()
